env:
jobs:
  fast_finish: true

  include:
    - language: node_js
      node_js: 10
      script:
        - npm run check

    - os: linux
      language: android
      jdk: oraclejdk8
      android:
        components:
          - platform-tools
          - tools
          - build-tools-28.0.3
          - android-21
          - android-28
          - sys-img-armeabi-v7a-android-21
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-google_play_services
      env:
        - JOB_NAME=ANDROID
      before_install:
        - nvm install 10
        - node --version
      install:
        - npm install
        - npm run link
      script:
        - npm run check
        - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
        - sudo sysctl -p
        - npm run build:android

    - os: osx
      language: objective-c
      osx_image: xcode10.1
      env:
        - JOB_NAME=IOS
      before_install:
        - nvm install 10
        - node --version
      install:
        - npm install
        - npm run link
        - (cd ios && pod install)
      script:
        - npm run tsc
        - npm run build:ios
